### ISSUE TITLE
Data preprocessing problem

### ISSUE THREAD

**Issue by TShoreWind** [Yzmblog/MonoHuman#19]
(Monohuman) u20@u20:/home/robot-disk/heruhan/tanhuafeng/3D_human/MonoHuman-main/tools/prepare_zju_mocap$ python prepare_dataset.py --cfg 387.yaml
  0%|                                                                                                                                                  | 0/540 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "prepare_dataset.py", line 194, in <module>
    app.run(main)
  File "/home/u20/anaconda3/envs/Monohuman/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/u20/anaconda3/envs/Monohuman/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "prepare_dataset.py", line 154, in main
    _, _, tpose_joints = smpl_model(np.zeros_like(poses), betas)
ValueError: not enough values to unpack (expected 3, got 2)
What does prepare_dataset.py do about this problem，Thank the author.

**Comment by TShoreWind** [comment]
@Yzmblog The problem has been solved
